[package]
name = "mio-serial"
version = "0.5.0"
authors = ["Zac Berkowitz <zac.berkowitz@gmail.com>"]
description = "A serial port implementation for mio"
license = "MIT"
homepage = "https://github.com/berkowski/mio-serial"
repository = "https://github.com/berkowski/mio-serial"
documentation = "http://docs.rs/mio-serial"
readme = "README.md"
keywords = ["rs232", "serial", "mio"]
categories = ["asynchronous", "hardware-support"]

[dependencies]
mio = "0.6"
serialport = { git = "https://gitlab.com/berkowski/serialport-rs", branch = "nix-testing" }

[target.'cfg(unix)'.dependencies]
nix = "0.9"

[[example]]
name = "serial_printline"
path = "examples/serial_printline.rs"
